server:
  port: 3000
  error:
    include-message: always

springdoc:
  default-produces-media-type: application/json

logging:
  level:
    org:
      springframework:
        web: DEBUG

spring:
  application:
    name: River-Tech-task
  profiles:
    active:
      - local
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

# Local profile settings
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:file:./src/main/resources/db/RiverTechTaskDb
    driverClassName: org.h2.Driver
    username: sa
    password:
    batch:
      jdbc:
        initialize-schema: always
