server:
  port: 3000

spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/db/RiverTechTaskDb
    driverClassName: org.h2.Driver
    username: sa
    password:
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
